spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eircare_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:eircare_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=${JWT_SECRET:a3fb96116a549ed321648c2b2a1ea81841b9f072d62b55b9d9403ef00c160c84}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB